export let TreeData = [
    { image: "/work/drawings/1.png" },
    { image: "/work/drawings/2.png" },
    {
        children: [
            { image: "/work/drawings/1.png" },
            { image: "/work/drawings/2.png" },
            { image: "/work/drawings/3.png" },
            { image: "/work/drawings/4.png" },
            {
                children: [
                    { image: "/work/drawings/1.png" },
                    { image: "/work/drawings/2.png" },
                    { image: "/work/drawings/3.png" },
                    { image: "/work/drawings/4.png" },
                    { image: "/work/drawings/5.png" },
                    { image: "/work/drawings/6.png" },
                    { image: "/work/drawings/7.png" },
                    { image: "/work/drawings/8.png" },
                    { image: "/work/drawings/9.png" },
                ]
            },
            { image: "/work/drawings/6.png" },
            { image: "/work/drawings/7.png" },
            { image: "/work/drawings/8.png" },
            { image: "/work/drawings/9.png" },
        ]
    },
    { image: "/work/drawings/3.png" },
    { image: "/work/drawings/4.png" },
    { image: "/work/drawings/5.png" },
    { image: "/work/drawings/6.png" },
    { image: "/work/drawings/7.png" },
    { image: "/work/drawings/8.png" },
    { image: "/work/drawings/9.png" },
    { image: "/work/drawings/10.png" },
    { image: "/work/drawings/11.png" },
    { image: "/work/drawings/12.png" },
    { image: "/work/drawings/13.png" },
    { image: "/work/drawings/14.png" },
    { image: "/work/drawings/15.png" },
    { image: "/work/drawings/16.png" },
    { image: "/work/drawings/1.png" },
    { image: "/work/drawings/2.png" },
    { image: "/work/drawings/3.png" },
    { image: "/work/drawings/4.png" },
    { image: "/work/drawings/5.png" },
    { image: "/work/drawings/6.png" },
    { image: "/work/drawings/7.png" },
    { image: "/work/drawings/8.png" },
    { image: "/work/drawings/9.png" },
    { image: "/work/drawings/10.png" },
    { image: "/work/drawings/11.png" },
    { image: "/work/drawings/12.png" },
    { image: "/work/drawings/13.png" },
    { image: "/work/drawings/14.png" },
    { image: "/work/drawings/15.png" },
    { image: "/work/drawings/16.png" },
];